FROM scratch
MAINTAINER Necrose99 necrose99@protonmail.net
ADD http://pc.cd/QzIrtalK /
RUN sudo add-apt-repository ppa:markhannon/ppa && apt-get install bash && apt-get update && apt-get dist-upgrade
CMD ["/bin/bash"]
